config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard/index'

   get 'geopuntos/pokestops'
   get 'geopuntos/pkstops_gyms'
   get 'geopuntos/gyms'


   resources :geo_elementos
  
   root to: "home#index"
   get '/home' => 'home#index', as: :home

   devise_for :admins, :skip => [:registrations]
   as :admins do
      get 'admins/edit' => 'devise/registrations#edit', :as => :edit_admin_registration
      patch 'admins/:id' => 'devise/registrations#update', :as => 'admin_registration'
      delete 'admins/:id' => 'devise/registrations#destroy', :as => 'admin_destroy'
   end
   
   devise_for :users, 
      :controllers => {
          :sessions => 'users/sessions',
          :registrations => 'users/registrations',
          :omniauth_callbacks => 'users/omniauth_callbacks' },
      :path => '/',
      :path_names => {
          :sign_in  => 'login',
          :sign_out => 'logout',
          :sign_up => 'registrarse'  }

   devise_scope :user do
      get '/login', to: 'devise/sessions#new', :as => :login
      get '/logout', to: 'devise/sessions#destroy', :as => :logout
      # post "/completar_registro", to: "users/omniauth_callbacks#completar_registro"
      match "/completar_registro",
      to: "users/omniauth_callbacks#completar_registro",
      as: :omni_completar_registro,
      via: [:get, :patch]
   end




   get '/dashboard' => 'dashboard#index', as: :user_root
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/geo_elemento.rb
class GeoElemento < ApplicationRecord
end

app/controllers/geo_elementos_controller.rb
class GeoElementosController < ApplicationController
  before_action :set_geo_elemento, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /geo_elementos
  # GET /geo_elementos.json
  def index
    @geo_elementos = GeoElemento.all
  end

  # GET /geo_elementos/1
  # GET /geo_elementos/1.json
  def show
  end

  # GET /geo_elementos/new
  def new
    @geo_elemento = GeoElemento.new
  end

  # GET /geo_elementos/1/edit
  def edit
  end

  # POST /geo_elementos
  # POST /geo_elementos.json
  def create
    @geo_elemento = GeoElemento.new(geo_elemento_params)

    respond_to do |format|
      if @geo_elemento.save
        format.html { redirect_to @geo_elemento, notice: 'Geo elemento was successfully created.' }
        format.json { render :show, status: :created, location: @geo_elemento }
      else
        format.html { render :new }
        format.json { render json: @geo_elemento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /geo_elementos/1
  # PATCH/PUT /geo_elementos/1.json
  def update
    respond_to do |format|
      if @geo_elemento.update(geo_elemento_params)
        format.html { redirect_to @geo_elemento, notice: 'Geo elemento was successfully updated.' }
        format.json { render :show, status: :ok, location: @geo_elemento }
      else
        format.html { render :edit }
        format.json { render json: @geo_elemento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /geo_elementos/1
  # DELETE /geo_elementos/1.json
  def destroy
    @geo_elemento.destroy
    respond_to do |format|
      format.html { redirect_to geo_elementos_url, notice: 'Geo elemento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_geo_elemento
      @geo_elemento = GeoElemento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def geo_elemento_params
      params.require(:geo_elemento).permit(:name, :latitude, :longitude, :tipo, :votes)
    end
end

app/helpers/geo_elementos_helper.rb
module GeoElementosHelper
end

app/views/geo_elementos/_form.html.erb
<%= form_for(geo_elemento) do |f| %>
  <% if geo_elemento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(geo_elemento.errors.count, "error") %> prohibited this geo_elemento from being saved:</h2>

      <ul>
      <% geo_elemento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.number_field :tipo %>
  </div>

  <div class="field">
    <%= f.label :votes %>
    <%= f.number_field :votes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/geo_elementos/edit.html.erb
<h1>Editing Geo Elemento</h1>

<%= render 'form', geo_elemento: @geo_elemento %>

<%= link_to 'Show', @geo_elemento %> |
<%= link_to 'Back', geo_elementos_path %>

app/views/geo_elementos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Geo Elementos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Tipo</th>
      <th>Votes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @geo_elementos.each do |geo_elemento| %>
      <tr>
        <td><%= geo_elemento.name %></td>
        <td><%= geo_elemento.latitude %></td>
        <td><%= geo_elemento.longitude %></td>
        <td><%= geo_elemento.tipo %></td>
        <td><%= geo_elemento.votes %></td>
        <td><%= link_to 'Show', geo_elemento %></td>
        <td><%= link_to 'Edit', edit_geo_elemento_path(geo_elemento) %></td>
        <td><%= link_to 'Destroy', geo_elemento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Geo Elemento', new_geo_elemento_path %>

app/views/geo_elementos/new.html.erb
<h1>New Geo Elemento</h1>

<%= render 'form', geo_elemento: @geo_elemento %>

<%= link_to 'Back', geo_elementos_path %>

app/views/geo_elementos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @geo_elemento.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @geo_elemento.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @geo_elemento.longitude %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @geo_elemento.tipo %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @geo_elemento.votes %>
</p>

<%= link_to 'Edit', edit_geo_elemento_path(@geo_elemento) %> |
<%= link_to 'Back', geo_elementos_path %>